// Code generated by mockery v2.40.2. DO NOT EDIT.

package domain

import mock "github.com/stretchr/testify/mock"

// MockMessenger is an autogenerated mock type for the Messenger type
type MockMessenger struct {
	mock.Mock
}

type MockMessenger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessenger) EXPECT() *MockMessenger_Expecter {
	return &MockMessenger_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: newMessage
func (_m *MockMessenger) Create(newMessage *NewMessage) (*Message, error) {
	ret := _m.Called(newMessage)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *Message
	var r1 error
	if rf, ok := ret.Get(0).(func(*NewMessage) (*Message, error)); ok {
		return rf(newMessage)
	}
	if rf, ok := ret.Get(0).(func(*NewMessage) *Message); ok {
		r0 = rf(newMessage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Message)
		}
	}

	if rf, ok := ret.Get(1).(func(*NewMessage) error); ok {
		r1 = rf(newMessage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessenger_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMessenger_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - newMessage *NewMessage
func (_e *MockMessenger_Expecter) Create(newMessage interface{}) *MockMessenger_Create_Call {
	return &MockMessenger_Create_Call{Call: _e.mock.On("Create", newMessage)}
}

func (_c *MockMessenger_Create_Call) Run(run func(newMessage *NewMessage)) *MockMessenger_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*NewMessage))
	})
	return _c
}

func (_c *MockMessenger_Create_Call) Return(_a0 *Message, _a1 error) *MockMessenger_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessenger_Create_Call) RunAndReturn(run func(*NewMessage) (*Message, error)) *MockMessenger_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: limit, offset
func (_m *MockMessenger) List(limit int, offset int) ([]*Message, error) {
	ret := _m.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*Message
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]*Message, error)); ok {
		return rf(limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int, int) []*Message); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Message)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessenger_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMessenger_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *MockMessenger_Expecter) List(limit interface{}, offset interface{}) *MockMessenger_List_Call {
	return &MockMessenger_List_Call{Call: _e.mock.On("List", limit, offset)}
}

func (_c *MockMessenger_List_Call) Run(run func(limit int, offset int)) *MockMessenger_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockMessenger_List_Call) Return(_a0 []*Message, _a1 error) *MockMessenger_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessenger_List_Call) RunAndReturn(run func(int, int) ([]*Message, error)) *MockMessenger_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTopic provides a mock function with given fields: topic, limit, offset
func (_m *MockMessenger) ListByTopic(topic string, limit int, offset int) ([]*Message, error) {
	ret := _m.Called(topic, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByTopic")
	}

	var r0 []*Message
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) ([]*Message, error)); ok {
		return rf(topic, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) []*Message); ok {
		r0 = rf(topic, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Message)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(topic, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessenger_ListByTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTopic'
type MockMessenger_ListByTopic_Call struct {
	*mock.Call
}

// ListByTopic is a helper method to define mock.On call
//   - topic string
//   - limit int
//   - offset int
func (_e *MockMessenger_Expecter) ListByTopic(topic interface{}, limit interface{}, offset interface{}) *MockMessenger_ListByTopic_Call {
	return &MockMessenger_ListByTopic_Call{Call: _e.mock.On("ListByTopic", topic, limit, offset)}
}

func (_c *MockMessenger_ListByTopic_Call) Run(run func(topic string, limit int, offset int)) *MockMessenger_ListByTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockMessenger_ListByTopic_Call) Return(_a0 []*Message, _a1 error) *MockMessenger_ListByTopic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessenger_ListByTopic_Call) RunAndReturn(run func(string, int, int) ([]*Message, error)) *MockMessenger_ListByTopic_Call {
	_c.Call.Return(run)
	return _c
}

// ListTopics provides a mock function with given fields: limit, offset
func (_m *MockMessenger) ListTopics(limit int, offset int) ([]string, error) {
	ret := _m.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListTopics")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]string, error)); ok {
		return rf(limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int, int) []string); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessenger_ListTopics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTopics'
type MockMessenger_ListTopics_Call struct {
	*mock.Call
}

// ListTopics is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *MockMessenger_Expecter) ListTopics(limit interface{}, offset interface{}) *MockMessenger_ListTopics_Call {
	return &MockMessenger_ListTopics_Call{Call: _e.mock.On("ListTopics", limit, offset)}
}

func (_c *MockMessenger_ListTopics_Call) Run(run func(limit int, offset int)) *MockMessenger_ListTopics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockMessenger_ListTopics_Call) Return(_a0 []string, _a1 error) *MockMessenger_ListTopics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessenger_ListTopics_Call) RunAndReturn(run func(int, int) ([]string, error)) *MockMessenger_ListTopics_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: hash
func (_m *MockMessenger) Read(hash string) (*Message, error) {
	ret := _m.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *Message
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*Message, error)); ok {
		return rf(hash)
	}
	if rf, ok := ret.Get(0).(func(string) *Message); ok {
		r0 = rf(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Message)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessenger_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockMessenger_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - hash string
func (_e *MockMessenger_Expecter) Read(hash interface{}) *MockMessenger_Read_Call {
	return &MockMessenger_Read_Call{Call: _e.mock.On("Read", hash)}
}

func (_c *MockMessenger_Read_Call) Run(run func(hash string)) *MockMessenger_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMessenger_Read_Call) Return(_a0 *Message, _a1 error) *MockMessenger_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessenger_Read_Call) RunAndReturn(run func(string) (*Message, error)) *MockMessenger_Read_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessenger creates a new instance of MockMessenger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessenger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessenger {
	mock := &MockMessenger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
