---
version: '3.7'

services:
  message-broker:
    image: trevatk/message-broker:latest
    container_name: message-broker
    hostname: message-broker.structx.docker
    restart: 'always'
    labels:
      - traefik.enable=true
      - traefik.http.routers.message-broker.service=message-broker
      - traefik.http.services.message-broker.loadbalancer.server.port=8080
      - traefik.http.routers.message-broker.rule=Host(`message-broker.structx.io`)
      - traefik.http.routers.message-broker.entrypoints=websecure
      - traefik.http.routers.message-broker.tls=true
      - traefik.http.routers.message-broker.tls.certresolver=cloudflareResolver
      - traefik.http.services.message-broker.loadbalancer.healthcheck.port=8080
      - traefik.http.services.message-broker.loadbalancer.healthcheck.interval=10s
      - traefik.http.services.message-broker.loadbalancer.healthcheck.path=/health
      - traefik.http.services.message-broker.loadbalancer.healthcheck.timeout=2s
      - traefik.http.services.message-broker.loadbalancer.healthcheck.scheme=http
    environment:
      - LOG_LEVEL=INFO
      - LOG_PATH=/var/log/broker/broker.log
      - SERVER_HTTP_PORT=8080
      - SERVER_GRPC_PORT=50051
      - KV_DIR=/var/lib/broker/kv
    ports:
      - 8080
      - 50051
      - 2112
    volumes:
      - ./kv:/var/lib/broker/kv:rw
      - ./logs:/var/log/broker:rw
    networks:
      - monitor-network
      - public-network

networks:
  monitor-network:
    external: true
  public-network:
    external: true
